name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          package-name: rack-idempotency_key
          release-type: ruby
          token: ${{secrets.GITHUB_TOKEN}}
          version-file: "lib/rack/idempotency_key/version.rb"
      - uses: actions/checkout@v3
        if: ${{steps.release.outputs.release_created}}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7.0
        if: ${{steps.release.outputs.release_created}}
      - run: bundle install
        if: ${{steps.release.outputs.release_created}}
      - run: ./bin/release
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        if: ${{steps.release.outputs.release_created}}
